.github/workflows/ci.yml
_CoqProject
coq-event-struct.opam
eventstructure.v
regmachine.v
relations.v
rfsfun.v
transitionsystem.v

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/28)

Rfsfun integration

---

.github/workflows/ci.yml
coq-event-struct.opam

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/32)

ci: fix finmap dependencies

---

eventstructure.v
regmachine.v
transitionsystem.v

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/31)

regmachine via Rfsfun

---

eventstructure.v
relations.v
utilities.v
wftype.v

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/34)

Refactoring of relations.v

---

regmachine.v
utilities.v

look https://github.com/volodeyka/event-struct/issues/33
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/35)

feat: add seq_in

---

README.md

I wanted to remove some redundant changes and broked everything... so that is a new PR. But all changes are here
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/36)

doc: improve README

---

coq-event-struct.opam

This PR is a follow-up on #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/37)

doc: fix description in opam file

---

coq-event-struct.opam

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/40)

doc[opam]: keywords, classification, authors

---

.github/workflows/ci.yml
_CoqProject
coq-event-struct.opam

See the commit messages for more detail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/39)

Coq 8.13 support

---

coq-event-struct.opam

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/41)

relation-algebra integration

---

README.md
inhtype.v
regmachine.v
utilities.v
wftype.v

This reverts the tactic name to its original one and gives proper credit to the author.
A follow-up on #44.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/45)

Keep original name for ssrnatlia

---

README.md
eventstructure.v
ident.v
inhtype.v
regmachine.v
relations.v
rfsfun.v
transitionsystem.v
utilities.v
wftype.v

Mathcomp-y naming convention for boolean `or` hints. A follow-up on #46.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/47)

Boolean OR hints

---

utilities.v

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/48)

refactor: section for seq_in, simplify a proof

---

utilities.v

It's in Mathcomp since version 1.10. This PR is a follow-up on #48.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/49)

Remove induction lemma `ltn_ind`

---

.gitignore
dependency-graph.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/52)

doc: script generating project's dependency graph

---

ident.v

The main contribution here is `nfresh`'s informal specification is fixed and the corresponding proofs provided.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/55)

refactor[ident]: fix docs, add nfresh spec, refactor proofs

---

utilities.v

These are some suggestions for PR #64 that I found hard to do via the code review interface. Notice the target branch is `ra-utils`, not `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/65)

Suggestions for PR #64

---

utilities.v

A couple of new lemmas for `seq_in` theory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/63)

Extend seq_in theory

---

_CoqProject
theories/concur/porf_eventstruct.v
theories/concur/transitionsystem.v
theories/lang/regmachine.v

* rename `eventstructure.v` into `porf_eventstruct.v`
* generalize labels 
* relational semantics of regmachine
* other minor renamings and cleanups

Eventstruct cleanup

---

theories/common/rewriting_system.v

In general we can't prove diamond property (for example for event structure without duplicates). But we can prove 
https://github.com/Event-Structures/event-struct/blob/40f9f2d9200515f27aceb929a558372e5f2e9e8e/theories/common/rewriting_system.v#L219-L221
And derive
https://github.com/Event-Structures/event-struct/blob/40f9f2d9200515f27aceb929a558372e5f2e9e8e/theories/common/rewriting_system.v#L223-L225
This PR dedicated to this problem

Lemmas about reflexive confluence

---

theories/concur/prime_eventstruct.v

1. Add definition of configurations in `PrimeC`
2. Show that it agrees with configurations in `Prime` and `PrimeG` (`cfgE` lemmas)
3. Using fact 2 prove that `<= e` is a configuration for `Prime` and `PrimeG` 
Also, I swapped `PrimeC` and `Prime`.

Configurations for `PrimeC`

---

README.md
theories/common/relalg.v
theories/common/utils.v

Fix minor warnings

---

README.md
theories/common/utils.v
theories/concur/lposet.v
theories/concur/pomset.v

* Prove that embedding is injective
* Prove that pair of injective homomorphisms between finite lposets implies the existence of a bijective homomorphism
* Instance of `porderType` on pomsets induced by bijective homomorphisms.

Partial Order on Pomset induced by bijective homomorphisms

---

theories/common/ident.v
theories/common/rel.v
theories/common/relalg.v
theories/common/utils.v
theories/concur/lts.v
theories/concur/pomset.v
theories/concur/prime_eventstruct.v

`lfsp_lang_lin` lemma stating that traces of poset LTS are linearizations

Poset LTS traces --> lineariazations

---

theories/common/rel.v
theories/common/utils.v
theories/concur/pomset.v

* intersection of pomset with relation and with another pomset
* relabeling of pomset
* restriction of pomset onto predicate

Some utilities for pomsets

---

theories/common/utils.v
theories/concur/lposet.v
theories/concur/pomset.v
theories/concur/pomset_lts.v
theories/concur/prime_eventstruct.v

Helper lemmas for morphisms (and corresponding preorders) on finitely supported posets.

lfsposet morphism utils

---

_CoqProject
theories/common/inhtype.v
theories/common/order.v
theories/common/utils.v
theories/concur/lposet.v
theories/concur/pomset.v
theories/concur/pomset_lts.v
theories/concur/porf_eventstruct.v
theories/concur/prime_eventstruct.v
theories/concur/relaxed.v
theories/lang/sharedmem.v

Add basic formalization of memory models, according to the paper "Causal Consistency: Beyond Memory" by Matthieu Perrin, Achour Mostefaoui, Claude Jard (PPoPP 2016)
* sequential consistency
* causal consistency
* pipelined consistency

Definitions of Relaxed Memory Models
