Event-Structures/event-struct

.github/workflows/ci.yml
coq-event-struct.opam

Here we pinned finmap to dev version via `before_install` in ci.yml
Also we removed coq.dev because it can't compile coq-equations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/29)

fix(ci): fix finmap version and remove coq.dev

---

inhtype.v
utilities.v

This commit also removes unused code that depends on `comp2`.
By the way,
```
(r \o2 ext f) a b -> (r \o2 ext (add f x)) a b
```
can be written as
```
subrel (relpre (ext f) r) (relpre (ext (add f x)) r)
```
after a bit of reshuffling of the quantifiers.
Upshot: no need to introduce `comp2`, the standard `relpre` could have been reused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/43)

refactor: relpre may be used instead of comp2

---

inhtype.v
regmachine.v
utilities.v

This removes spurious `none` notation.
And refactors `some` to `Some` because `some` is intended
to be used as a function passed to higher-order functions.
This PR is a follow-up of #43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/44)

Remove none notation

---

eventstructure.v
transitionsystem.v
utilities.v

- Removed `refleqP` because it repeats the idiomatic `apply/view1/view2` tactic.
- Changed the implicit status of the arguments of a couple of view lemmas.
In general, `reflect`-lemmas should have their "simple" arguments maximally-inserted implicit.
- Renamed `exists_eq` into `exists_equiv`.
- Removed `and_eq` lemma because it's `andb_id2l` from ssrbool.v.
- Added two helper lemmas about causality and freshness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/51)

refactor: logical lemmas from utilities

---

eventstructure.v
wftype.v

`wf` -> `wfb` and `wf_ind` -> `wfb_ind` ("b" means "Boolean").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/53)

refactor: wftype's docs, imports, names, proofs

---

eventstructure.v
ident.v
regmachine.v
relations.v
rfsfun.v
transitionsystem.v
wftype.v

This PR's scope is just imports across the whole project nothing else has been touched.
This simplifies the project's dependency graph and should speed compilation time a bit (not that it matters in our particular case).
Partly done using https://github.com/JasonGross/coq-tools
```
coq-tools/minimize-requires.py --all -f _CoqProject
```
and partly manually.
This PR depends on #53 (I noticed there is room for import refactoring while working on #53).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/54)

refactor: minimize imports and reorganize them a bit

---

relations.v

1) rename `strict` --> `strictify` (verb form, the name is debatable)
2) prove specification lemmas about `strictify` using relation-algebra
* A minor related problem --- import of relation-algebra also brings in scope some definitions from vanilla Coq, which shadow `ssrbool` definitions (see lines 11-13). Any ideas on how to avoid this?

strict spec using relation-algebra

---

_CoqProject
monoid.v

This PR features the monoid and partial monoid structures (the latter inherits from the former). The partial monoid is intended to be a base class for synchronization algebra later #59. Partiality is encoded using the binary orthogonality relation (see [1] for details).
Why did we decide to invent the wheel here? Below are alternative formalizations of monoids and the reasons why we abandoned them. 
1) [mathcomp](https://github.com/math-comp/math-comp/blob/17dd3091e7f809c1385b0c0be43d1f8de4fa6be0/mathcomp/ssreflect/bigop.v#L328) 
Here the monoids are used primarily in the context of so-called big operations. The canonical instances are linked to operations themselves rather than to types. We decided that for our use cases, it makes more sense to attach the instance to the type. 
2) …

Monoid and Partial Monoid

---

eventstructure.v
regmachine.v
transitionsystem.v
utilities.v

In this PR our semantics of one-thread program was upgraded to the semantics of multi-thread program. 
Here were made some technical things, and it is a bit difficult for me to explain the main problem offline. I think the better way would be to discuss this PR at the meeting
I don't know if my solution is a good idea, but anyway it is temporal: we are going to get rid of programs with fixed number of threads from the very beginning

Semantics for multi-thread program

---

eventstructure.v
relations.v
utilities.v

To check acyclicity of finite function (`fsfun`) we should fist define it's transitive closure
Consider we have some `f : {fsfun : K -> V with dflt}` with is not decreasing. Clearly, `sfrel f` is not well-founded but we steel can define it's transitive closure.  
Here in SSReflect we 
https://github.com/math-comp/math-comp/blob/8e859e628404c50c8191f30489abf4e799f46f8d/mathcomp/ssreflect/fingraph.v#L48-L75
definition of `dfs` and some helpful lemmas.  Unfortunately we can't use such a definition because we have `fsfun` but not function of type (`T -> seq T`), where `T : finType`. Here I propose a way to use mathcomp's `dfs` to solve our goal: we should define our `dfs` version (`fdfs` here) and show that it is equivalent to original `dfs`. But I faced with rather technically difficult …

Adding lemmas for checking acyclicity of finite function

---

coq-event-struct.opam
eventstructure.v
relations.v
transitionsystem.v
utilities.v

This PR includes.
* An instance of relation-algebra's `monoid` structure for decidable relations of type `rel T` over `T : eqType`. 
Note that this monoid instance only provides: lattice operations (union, intersection, top, bottom, etc), identity relation `eq_op`, and converse `cnv`. Despite this limitation, still it allows us to use some notations ~~and lemmas~~ from relation-algebra. ~~Another drawback is that it requires us to use a custom fork of relation-algebra: https://github.com/eupp/relation-algebra/tree/monoid-decoupling.~~ I temporarily disabled all features that depend on the custom fork. It seems we currently don't need them. We'll see whether the custom fork will be accepted and merged into `relation-algebra`. 
* A refactoring of `sfrel`. In more detail, it reverses the …

Relation Algebra instance for decidable relations & sfrel refactoring 

---

theories/common/rewriting_system.v

Here I add lemma `confl_sub`
If you take 
`S := exec_event_structure`
`p := dom_consistency`
`r1 := AddEvent.tr`
`e1 := eqv`
`T := cexec_event_structure`
`r2 :=  AddEvent.tr` contracted (how?) on `cexec_event_structure` (lets denote it as `CAddEvent.tr`)
`e2 := AddEvent.eqv` contracted (how?) on `cexec_event_structure` (lets denote it as `CAddEvent.eqv`)
`f := val`
Then `conflict_sub` says that 
```Coq
conflunent_eqv (AddEvent.tr ⊓  dom_consistency ×  dom_consistency) AddEvent.eqv
```
implies
```Coq
confluen_eqv CAddEvent.tr CAddEvent.eqv
```

Rewriting System

---

theories/common/utils.v

The version we had is not reliable across the supported Coq versions.

refactor(utils): remove intro-patterns defined in Mathcomp 1.12

---

theories/concur/pomset.v
theories/concur/porf_eventstruct.v
theories/concur/prime_eventstruct.v

This PR is a retake on `pomset.v`. 
It features several changes. 
1. In `pomset.v` the `Pomset` structure is renamed into `LPoset` (labeled partially ordered set) to avoid confusion. A labelling function is embedded into `LPoset` hierarchy. 
2. An axiom of finite cause is removed from `LPoset` (top of the hierarchy) and is moved to a new structure `Elem.eventStruct` that is an elementary event structure (which is a labelled poset + axiom if finite cause). Elementary event structures are then inherited by various subclasses of prime event structures, that is prime event structures with binary and general conflict. 
3. Definition of homomorphism between labelled posets is given, together with basic combinators (`id`, `tr`) and notations.

Labelled posets and their homomorphisms

---

theories/concur/pomset.v
theories/concur/porf_eventstruct.v
theories/concur/prime_eventstruct.v

This PR features:
* definition of pomset language as a set of labelled posets `lPoset.eventType L -> Prop` invariant under labelled posets isomorphism;
* `lattice` instance for pomset languages (integration with `relation-algebra` package);
* definition of _stronger-than_ and _supported-by_ preorders over pomset languages.

Pomset language definition and simple properties

---

theories/common/relalg.v
theories/concur/pomset.v
theories/concur/porf_eventstruct.v

The main contribution of this PR is the notion of the scheduling of `lposet` and `pomset`. 
A schedule of labelled poset is a set of its totally ordered extensions. Scheduling of a pomset is a union of these extensions for each of the posets belonging to the pomset. Scheduling will be used later to connect pomset semantics with trace semantics. 
The main proven lemmas are `schedule_hom`, `scheduling_unistronger` and `scheduling_stronger` which describe how schedulings of `lposets` and `pomsets` behave with respect to homomorphisms. 
An auxiliary very helpful notion developed in this PR is `Ext` --- an extension of `lposet` `p` by another `lposet` `q` under the assumption that there exists a homomorphism from `p` to `q` (or in other words, the order in `q` should not contradict the order …

Scheduling of a Pomset

---

README.md
_CoqProject
theories/common/utils.v
theories/concur/lts.v

A basic theory of labelled transition systems, (linear) traces and simulation relations. 
In subsequent PRs we are going to reconcile LTS semantics (interleaving semantics) with pomset and event structure semantics (non-interleaving). 
Two important lemmas proved in this PR are `sim_lang` and `bisim_lang`. 
These lemmas assert that a language accepted by one LTS can also be accepted by another one if there exists a simulation (bisimulation) relation between the initial states (see the formal statement in the code).

Initial PR with LTS theory

---

theories/concur/lts.v

Introduce `adjoin` operation to concatenate traces (returns empty trace if concatenated traces are not adjoint).
Use new combinators on traces to simplify `sim_lang` lemma proof.

Adjoin operation on traces 

---

theories/common/rel.v
theories/common/relalg.v
theories/common/rewriting_system.v
theories/concur/porf_eventstruct.v

* set implicit arguments for `clos_trans` and related definitions from vanilla Coq library.
* shorter names for lemmas relating closure operation definitions from vanilla coq and relation-algebra package
* prove `connect_strP` lemma for reflexive-transitive closure of finite relations

Minor changes in `relalg.v `

---

README.md
_CoqProject
theories/common/order.v
theories/common/utils.v

This PR adds a subclass of downward finite partial orders, i.e. partial orders where each element has only a finite number of predecessors. The set of predecessors of an element is also called a principal ideal, so in other words is that partial order should have finite principal ideal. In Coq it is encoded as function `pideal : E -> {fset E}` together with axiom `forall x y : T, x \in (pideal y) = (x <= y)`.
Moreover, this condition allows us to have upward closure operator `up_clos` which returns decidable predicate (as opposed to `Prop` predicate in the general case). In this PR we also prove that `up_clos` satisfies [Kuratowsky closure axioms](https://en.wikipedia.org/wiki/Kuratowski_closure_axioms).

Downward-finite partial order

---

theories/common/utils.v
theories/concur/porf_eventstruct.v
theories/concur/prime_eventstruct.v

* Remove elementary event structures `Elem.EventStruct`, instead inherit `PrimeC` from `DwFinPOrder`
* Remove `PrimeG` event structures, define `gcf` and `cf` on `PrimeC` event structures.
* Add `gcf` and `cf` morhpism lemmas. 
* Inherit `Prime` from `PrimeC`, prove `bgcfP` and `bgcfE` lemmas to express general conflict through binary conflict.

Simplify Hierarchy of Event Structures

---

coq-eventstruct.opam
theories/common/utils.v
theories/concur/pomset.v

Several auxiliary definitions and lemmas for pomsets. 
* `lFsPreposet.Build.build` to build `lfspreposet` from finite graph (labeling function and covering relation/Hasse diagram)
* `lfsp_tseq` --- topological sorting of poset
* `lfsp_idx` --- index of event in topological sorting 
* `lfsp_event` --- get event by its index
* `lfsposet_eqP` --- reflect lemma for equality over lposets
* `choiceType` and `countType` instances for `lfspreposet`, `lfsposet`, `pomset`.
* other minor lemmas

Pomset utils

---

theories/common/ident.v
theories/common/order.v
theories/common/utils.v
theories/concur/lposet.v
theories/concur/lts.v
theories/concur/pomset.v
theories/concur/pomset_lts.v
theories/concur/prime_eventstruct.v
theories/concur/transitionsystem.v

The main contribution of this PR is lemma `tomset_labelsK`, which is a part of the proof that tomsets are isomorphic to sequences. 
Additional features introduced in this PR:
*  `conseq_num`  property of posets, asserting that events of the poset form a consecutive sequence of events, from `0` to `n`
* changed definition of `fresh_seq` to simplify proof of `tomset_labelsK`, as a by-product simplify proofs in `pomset_lts.v` to remove unnecessary case-analysis.

Tomset Utils

---

theories/common/ident.v
theories/common/inhtype.v
theories/common/rel.v
theories/common/relalg.v
theories/common/utils.v
theories/concur/pomset.v
theories/concur/pomset_lts.v
theories/concur/prime_eventstruct.v
theories/lang/regmachine.v
theories/lang/relaxed.v
theories/lang/sharedmem.v

1) Use `lfsp_eventset` instead of `finsupp` to get a set of events of a pomset
2) Use `L : botType`  as a type of labels, avoid passing `bot` value explicitly

Refactor Pomset's events and labels representation
